version: 21
jobs:
- name: 同步下游仓库
  steps:
  - !PushRepository
    name: 推送到gitee
    remoteUrl: https://gitee.com/ajieOwO/ajielog.git
    userName: ajieOwO
    passwordSecret: push_to_gitee_ajieOwO
    force: true
    condition: ALWAYS
  - !PushRepository
    name: 推送到github
    remoteUrl: https://github.com/ajieOwO/ajielog.git
    userName: ajieOwO
    passwordSecret: push_to_github_ajieOwO
    force: true
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
