version: 21
jobs:
- name: 同步到github
  steps:
  - !PushRepository
    name: 推送到github
    remoteUrl: https://github.com/ajieOwO/ajielog.git
    userName: ajieOwO
    passwordSecret: push_to_github
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    projects: ajieOwO/AjieLog
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: 同步到gitee
  steps:
  - !PushRepository
    name: push_to_gitee
    remoteUrl: https://gitee.com/ajieOwO/ajielog.git
    userName: ajieOwO
    passwordSecret: push_to_gitee
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
